import AppKit

/// Clipboard history: whatever you copy, text or an image, hangs on the line
/// too. macOS has no notification for clipboard changes, so the change
/// count is checked twice a second, which costs next to nothing.
///
/// Each clip is written to Sinampay's own folder, so the rest of the app
/// treats it like any other file: it survives a relaunch, drags out, and is
/// deleted when it leaves the line.
@MainActor
final class ClipboardWatcher {
    nonisolated static let folder = AppFolders.base.appendingPathComponent("Clipboard", isDirectory: true)

    /// The change count after Sinampay itself wrote to the clipboard, by
    /// copying a card. That is not a new clip.
    static var ownChangeCount = -1

    var isEnabled: Bool {
        get { !UserDefaults.standard.bool(forKey: "clipboardOff") }
        set {
            UserDefaults.standard.set(!newValue, forKey: "clipboardOff")
            newValue ? start() : stop()
        }
    }

    private let onNew: (URL) -> Void
    private var lastChange = NSPasteboard.general.changeCount
    private var lastText: String?
    private var timer: Timer?

    /// Password managers and other well-behaved apps mark what should never
    /// be kept in a history. See nspasteboard.org.
    private static let privateTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    init(onNew: @escaping (URL) -> Void) {
        self.onNew = onNew
    }

    func start() {
        guard isEnabled, timer == nil else { return }
        // Only what is copied from now on; the clipboard as it was is not news.
        lastChange = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        guard lastChange != Self.ownChangeCount else { return }

        let types = Set(pb.types ?? [])
        guard types.isDisjoint(with: Self.privateTypes) else { return }
        // Files copied in Finder already live somewhere; a screenshot taken
        // straight to the clipboard is an image and does count.
        guard !types.contains(.fileURL) else { return }

        if let text = pb.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard text != lastText else { return }
            lastText = text
            if let url = write(Data(text.utf8), ext: "txt") { onNew(url) }
        } else if let image = NSImage(pasteboard: pb), let png = pngData(image) {
            lastText = nil
            if let url = write(png, ext: "png") { onNew(url) }
        }
    }

    private func write(_ data: Data, ext: String) -> URL? {
        let fm = FileManager.default
        try? fm.createDirectory(at: Self.folder, withIntermediateDirectories: true)
        let stamp = Self.stampFormatter.string(from: Date())
        let url = Self.folder.appendingPathComponent("Clip \(stamp) \(UUID().uuidString.prefix(4))").appendingPathExtension(ext)
        do {
            try data.write(to: url, options: .atomic)
            return url
        } catch {
            log.error("Could not keep clip: \(error.localizedDescription, privacy: .public)")
            return nil
        }
    }

    private static let stampFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd 'at' HH.mm.ss"
        return f
    }()

    // MARK: Kinds of item

    nonisolated static func isClip(_ url: URL) -> Bool { AppFolders.contains(url, in: folder) }

    nonisolated static func isText(_ url: URL) -> Bool { url.pathExtension.lowercased() == "txt" }

    nonisolated static func text(of url: URL) -> String? {
        guard isText(url), let data = try? Data(contentsOf: url) else { return nil }
        return String(decoding: data, as: UTF8.self)
    }
}

// MARK: Text cards

/// A copied text drawn as a small note, the size of a screenshot card, so
/// it can hang, fly, fall and be dragged like any photo.
func makeTextThumbnail(_ text: String) -> NSImage? {
    let size = NSSize(width: 272, height: 200), scale: CGFloat = 2
    guard let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: Int(size.width * scale),
                                     pixelsHigh: Int(size.height * scale), bitsPerSample: 8,
                                     samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                                     colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0) else { return nil }
    rep.size = size
    NSGraphicsContext.saveGraphicsState()
    defer { NSGraphicsContext.restoreGraphicsState() }
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)

    // Warm paper with the fiesta stripe along the top: the note.
    let bounds = NSRect(origin: .zero, size: size)
    Palette.paper.setFill()
    bounds.fill()
    let stripe = size.width / CGFloat(Palette.banderitas.count)
    for (i, c) in Palette.banderitas.enumerated() {
        c.setFill()
        NSRect(x: CGFloat(i) * stripe, y: size.height - 8, width: stripe + 0.5, height: 8).fill()
    }

    let shown = String(text.trimmingCharacters(in: .whitespacesAndNewlines).prefix(400))
    let style = NSMutableParagraphStyle()
    style.lineBreakMode = .byWordWrapping
    style.lineSpacing = 2
    let attrs: [NSAttributedString.Key: Any] = [
        .font: NSFont.systemFont(ofSize: 19, weight: .medium),
        .foregroundColor: Palette.ink,
        .paragraphStyle: style,
    ]
    NSAttributedString(string: shown, attributes: attrs)
        .draw(with: NSRect(x: 16, y: 14, width: size.width - 32, height: size.height - 8 - 14 - 14),
              options: [.usesLineFragmentOrigin, .truncatesLastVisibleLine])

    let image = NSImage(size: size)
    image.addRepresentation(rep)
    return image
}

func pngData(_ image: NSImage) -> Data? {
    guard let tiff = image.tiffRepresentation, let rep = NSBitmapImageRep(data: tiff) else { return nil }
    return rep.representation(using: .png, properties: [:])
}
